[package]
name = "net_man"
version = "0.1.0"
authors = ["Ahmed Hamdy <ahmedhamdyau@gmail.com>"]

[lib]
name = "net_man"  
crate-type = ["dylib"]  

[[bin]]
name ="net_use"
path = "src/bin/main.rs"

[dependencies]
